# Generated by Django 5.1.5 on 2025-02-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_link_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('finance', 'Finance Tracker'), ('fit_weather', 'Fitness Weather App'), ('business_finder', 'Local Business Finder')], default='portfolio', max_length=50),
        ),
    ]
