# Generated by Django 5.1.5 on 2025-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FINANCE', 'Fiinance Tracker'), ('BLOG', 'Personal Blog'), ('FIT_WEATHER', 'Fitness Weather App'), ('BUSINESS_LOCATOR', 'Local Business Finder'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
