# Generated by Django 5.1.5 on 2025-02-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_project_type_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FINANCE', 'Fiinance Tracker'), ('BLOG', 'Personal Blog'), ('FIT_WEATHER', 'Weather App'), ('BUSINESS_FINDER', 'Business Finder'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
