# Generated by Django 5.1.5 on 2025-02-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_project_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='github',
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FINANCE', 'Fiinance Tracker'), ('BLOG', 'Personal Blog'), ('WORKER_MANAGEMENT', 'Contract Worker Management'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
