# Generated by Django 5.1.5 on 2025-02-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_link_project_github_alter_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the technology (e.g., Python, Django)', max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='technology_icons/')),
            ],
            options={
                'verbose_name': 'Technologies',
            },
        ),
    ]
