# Generated by Django 5.1.5 on 2025-03-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_technology_options_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('FINANCE', 'Fiinance Tracker'), ('BLOG', 'Personal Blog'), ('WORKER_MANAGEMENT', 'Contract Worker Management'), ('PORTFOLIO_SITE', 'Portfolio Site'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
