# Generated by Django 5.0.3 on 2025-04-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current',
            field=models.BooleanField(default=False, help_text="Check if this is a project you're currently working on"),
        ),
    ]
