# Generated by Django 5.0.3 on 2025-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website',
            field=models.URLField(blank=True, help_text='Live website URL', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('DEVOPS', 'DevOps Projects'), ('AUTOMATION', 'AI & Automation'), ('FIT_WEATHER', 'Fitness & Weather'), ('BUSINESS_FINDER', 'Business Finder'), ('BLOG', 'Blog'), ('WEATHER_APP', 'Weather App'), ('MACHINE_LEARNING', 'Machine Learning'), ('DATA_VISUALIZATION', 'Data Visualization'), ('WEB_DEVELOPMENT', 'Web Development'), ('MOBILE_APP', 'Mobile App Development'), ('E_COMMERCE', 'E-Commerce'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
